// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOb8FoB4B94iXE1w6vDztlKMo89asHK5Y',
    appId: '1:117009758684:web:224683cbffc5fe1638f719',
    messagingSenderId: '117009758684',
    projectId: 'mcart-47ccb',
    authDomain: 'mcart-47ccb.firebaseapp.com',
    storageBucket: 'mcart-47ccb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilaAIROJmkd98ORKarz31hSTsSu8uDt4',
    appId: '1:117009758684:android:6925965e55b2a41d38f719',
    messagingSenderId: '117009758684',
    projectId: 'mcart-47ccb',
    storageBucket: 'mcart-47ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42zklef9pJ75UBmaOUjD5xOBgqf2eM_I',
    appId: '1:117009758684:ios:d5beb24fb19865b538f719',
    messagingSenderId: '117009758684',
    projectId: 'mcart-47ccb',
    storageBucket: 'mcart-47ccb.appspot.com',
    iosClientId: '117009758684-dk35q4s9skncrgia8n2bovp13d24nkhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42zklef9pJ75UBmaOUjD5xOBgqf2eM_I',
    appId: '1:117009758684:ios:d5beb24fb19865b538f719',
    messagingSenderId: '117009758684',
    projectId: 'mcart-47ccb',
    storageBucket: 'mcart-47ccb.appspot.com',
    iosClientId: '117009758684-dk35q4s9skncrgia8n2bovp13d24nkhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcart',
  );
}
